Readme a
KawakamiYuka0424/chat-space pull request #1
Opened 2019-05-09 03:35 UTC by KawakamiYuka0424

2019-05-09 03:58 UTC, TOMARUMARU commented
差分がありません...

2019-05-09 05:03 UTC, KawakamiYuka0424 commented
ご指摘ありがとうございます。
README_aブランチとマスターブランチに差分が無いと言う事でよろしかったでしょうか？

2019-05-09 07:48 UTC, miyagit reviewed
こちら削除の変更点しか無いのですが。。

2019-05-12 08:21 UTC, ghost requested changes
一点だけ修正を御願い致します

2019-05-12 08:21 UTC, hiroki5123 commented on README.md
> +|group_name|string|null: false, unique: true|
nameでいいかと思います

2019-05-13 08:25 UTC, KawakamiYuka0424 commented on README.md
> +|group_name|string|null: false, unique: true|
ご指摘ありがとうございます！

2019-05-13 08:29 UTC, i-date approved these changes
お疲れ様でした、LGTMです^^ 

ご参考までに。
レビューを依頼する際には、[WIP]は外してからレビューを依頼するといいでしょう^^
WIP = 作業中 なので、一通り作業が完了→WIP外す→レビュー依頼、という流れになります！

2019-05-13 08:32 UTC, KawakamiYuka0424 commented
ありがとうございます！

2019-05-13 08:42 UTC, merged